model_name: "Qwen/Qwen2.5-14B"
output_dir: "../outputs/qwen2.5-14b-sft-s1-pro"
run_name: "qwen14b-sft-s1-processed"
resume_from_checkpoint: False
checkpoint_path: "../outputs/qwen2.5-3b-grpo-test/checkpoint-540"
learning_rate: 1e-6
adam_beta1: 0.9
adam_beta2: 0.95
weight_decay: 1e-4
warmup_steps: 25
lr_scheduler_type: constant_with_warmup
logging_steps: 1
bf16: True
bf16_full_eval: True
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
gradient_checkpointing: True
max_prompt_length: 256
max_completion_length: 32768
num_train_epochs: 5
save_steps: 1000
max_grad_norm: 0.1
report_to: wandb
max_steps: -1
log_completions: True
evaluation_strategy: steps
eval_steps: 50
eval_on_start: False 
